### Health Check: Enpoint para verificar que el servidor esté activo
GET http://127.0.0.1:8000/health


### Registrar nuevo usuario - Caso exitoso
POST http://127.0.0.1:8000/api/v1/auth/registrar
Content-Type: application/json

{
  "email": "carlos@example.com",
  "contrasena": "password123"
}

### Registrar nuevo usuario - Caso 2
POST http://127.0.0.1:8000/api/v1/auth/registrar
Content-Type: application/json

{
  "email": "maria.garcia@test.com",
  "contrasena": "secure2024"
}


### Registrar usuario - Error: contraseña sin número
POST http://127.0.0.1:8000/api/v1/auth/registrar
Content-Type: application/json

{
  "email": "test@example.com",
  "contrasena": "password"
}


### Registrar usuario - Error: contraseña sin letra
POST http://127.0.0.1:8000/api/v1/auth/registrar
Content-Type: application/json

{
  "email": "test@example.com",
  "contrasena": "12345678"
}


### Registrar usuario - Error: contraseña muy corta
POST http://127.0.0.1:8000/api/v1/auth/registrar
Content-Type: application/json

{
  "email": "test@example.com",
  "contrasena": "pass1"
}


### Registrar usuario - Error: email inválido
POST http://127.0.0.1:8000/api/v1/auth/registrar
Content-Type: application/json

{
  "email": "correo-invalido",
  "contrasena": "password123"
}



### Login - Caso exitoso
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "carlos@example.com",
  "contrasena": "password123"
}


### Login - Caso 2
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "maria.garcia@test.com",
  "contrasena": "secure2024"
}


### Login - Email no registrado (debería funcionar en mock)
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "noexiste@example.com",
  "contrasena": "password123"
}
